version: '3.0'

services:
  nginx:
    restart: always
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 3050:80
    depends_on:
      - api
      - client

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis

  client:
    build:
      context: client
      dockerfile: Dockerfile
      target: dev
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    build:
      context: server
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
